d /run/bored-manager 0750 bored-manager bored-manager -
d /var/lib/bored-manager 0750 bored-manager bored-manager -
d /var/cache/bored-manager 0750 bored-manager bored-manager -
d /var/cache/bored-manager/staged 0750 bored-manager bored-manager -
