import { useState, type FormEvent } from "react";
import { CheckCircle2, Container, Fingerprint, KeyRound, Plus, Server, ShieldAlert, Wifi, X } from "lucide-react";
import { useApi } from "../api/context";
import { useAsyncData } from "../hooks/useAsyncData";
import { relativeTime } from "../lib/format";
import type { DockerHost } from "../types";
import { Badge, Button, EmptyState, ErrorPanel, LoadingPanel, PageHeader, Panel, StatusBadge, Toast } from "../components/ui";

export function DockerHostsPage() {
  const api = useApi();
  const resource = useAsyncData<DockerHost[]>((signal) => api.listDockerHosts(signal), [api]);
  const [showAdd, setShowAdd] = useState(false);
  const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState<string>();
  const [form, setForm] = useState({ name: "", address: "", port: 22, user: "", credentialRef: "", fingerprint: "", knownHostLine: "" });
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); try { await api.createDockerHost(form); setShowAdd(false); setNotice(`${form.name} is connected.`); resource.reload(); setForm({ name: "", address: "", port: 22, user: "", credentialRef: "", fingerprint: "", knownHostLine: "" }); } finally { setBusy(false); } }
  return <div className="page"><PageHeader eyebrow="Container infrastructure" title="Docker hosts" description="Local socket access and strict host-key-verified SSH connectors." actions={<Button onClick={() => setShowAdd(true)}><Plus size={16} /> Connect remote host</Button>} />
    <div className="security-callout docker-warning"><ShieldAlert size={20} /><div><strong>Docker access is root-equivalent</strong><p>Only register trusted engines. Bored Manager never enables an unauthenticated TCP socket and never changes your firewall.</p></div></div>
    {resource.loading ? <LoadingPanel label="Checking Docker hosts" /> : resource.error ? <ErrorPanel message={resource.error} retry={resource.reload} /> : !resource.data?.length ? <Panel><EmptyState title="No Docker hosts connected">Register a rootful Ubuntu Docker Engine over SSH, or enable the local socket in Settings.</EmptyState></Panel> : <div className="host-grid">{resource.data.map((host) => <Panel className="host-card" key={host.id}><header><span className={`host-icon ${host.status}`}><Server size={20} /></span><div><h2>{host.name}</h2><p>{host.endpoint}</p></div><StatusBadge value={host.status} /></header><div className="engine-version"><Container size={17} /><span><small>Docker Engine</small><strong>{host.engineVersion}</strong></span><Badge tone={host.engineVersion === "28.5.1" ? "warning" : "success"}>API {host.apiVersion}</Badge></div><dl><div><dt>Transport</dt><dd>{host.transport === "local_unix" ? "Local Unix socket" : "SSH to Unix socket"}</dd></div><div><dt>Managed agents</dt><dd>{host.agents}</dd></div><div><dt>Containers</dt><dd>{host.containers}</dd></div><div><dt>Last verified</dt><dd>{relativeTime(host.lastChecked)}</dd></div>{host.fingerprint && <div><dt>Host key</dt><dd className="mono">{host.fingerprint}</dd></div>}</dl><footer><button><Wifi size={15} /> Test connection</button><button>Open host</button></footer></Panel>)}</div>}
    {showAdd && <div className="modal-backdrop"><form className="modal" role="dialog" aria-modal="true" aria-labelledby="host-title" onSubmit={submit}><header><div><p className="eyebrow">Strict SSH connector</p><h2 id="host-title">Connect a Docker host</h2></div><button type="button" aria-label="Close dialog" onClick={() => setShowAdd(false)}><X size={19} /></button></header><p>Bored Manager uses a preloaded encrypted systemd credential. Passwords, SSH agents, forwarding, implicit SSH config, and unknown host keys are rejected.</p><div className="field-grid"><label>Display name<input autoFocus required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="dockyard-03" /></label><label>SSH port<input type="number" required value={form.port} min="1" max="65535" onChange={(e) => setForm({ ...form, port: Number(e.target.value) })} /></label></div><div className="field-grid"><label>SSH user<input required value={form.user} onChange={(e) => setForm({ ...form, user: e.target.value })} placeholder="docker-admin" /></label><label>Credential reference<input required value={form.credentialRef} onChange={(e) => setForm({ ...form, credentialRef: e.target.value })} placeholder="ssh-dockyard-03.key" /></label></div><label>IP address or DNS name<input required value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} placeholder="10.24.4.12" /></label><label>Full known_hosts line<textarea required value={form.knownHostLine} onChange={(e) => setForm({ ...form, knownHostLine: e.target.value })} placeholder="dockyard-03 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5..." /></label><label>Out-of-band SHA-256 fingerprint<div className="input-with-icon"><Fingerprint size={17} /><input required pattern="SHA256:.*" value={form.fingerprint} onChange={(e) => setForm({ ...form, fingerprint: e.target.value })} placeholder="SHA256:..." /></div></label><div className="security-caption"><KeyRound size={16} /> The full key is validated against this fingerprint before any SSH connection.</div><footer><Button variant="ghost" type="button" onClick={() => setShowAdd(false)}>Cancel</Button><Button type="submit" busy={busy}><CheckCircle2 size={16} /> Verify & connect</Button></footer></form></div>}
    {notice && <Toast title="Docker host connected" message={notice} onClose={() => setNotice(undefined)} />}
  </div>;
}
