import { CheckCircle2, Download, ExternalLink, FileCheck2, PackageCheck, Rocket, ShieldCheck } from "lucide-react";
import { useApi } from "../api/context";
import { useAsyncData } from "../hooks/useAsyncData";
import { dateTime } from "../lib/format";
import type { Release } from "../types";
import { Badge, Button, EmptyState, ErrorPanel, LoadingPanel, PageHeader, Panel } from "../components/ui";

export function ReleasesPage() {
  const api = useApi(); const resource = useAsyncData<Release[]>((signal) => api.listReleases(signal), [api]);
  const current = resource.data?.find((release) => release.current);
  return <div className="page"><PageHeader eyebrow="Signed lifecycle" title="Releases & updates" description="Verify, stage and roll out package-based updates with a known-good rollback." actions={<Button variant="secondary" onClick={resource.reload}><FileCheck2 size={16} /> Refresh metadata</Button>} />
    <Panel className="release-hero"><span className="release-icon"><PackageCheck size={27} /></span><div><p className="eyebrow">Installed release</p><h2>{current ? `Bored Manager ${current.version}` : "Unsigned development state"}</h2><p>{current?.notes ?? "No published, verified release metadata is exposed by this pre-alpha manager."}</p><div>{current?.signed ? <Badge tone="success"><ShieldCheck size={12} /> signature verified</Badge> : <Badge tone="warning">verification unavailable</Badge>}{current && <Badge>manager + agent {current.compatibleAgent}</Badge>}</div></div><aside><span><CheckCircle2 size={17} /> {current ? "Release metadata loaded" : "Stable promotion blocked"}</span><small>{current ? `Published ${dateTime(current.publishedAt)}` : "No certification record"}</small><Button disabled={!current}><Rocket size={16} /> Plan rollout</Button></aside></Panel>
    <Panel><div className="panel-heading"><div><h2>Release history</h2><p>Offline Ed25519 signatures, SHA-256 manifests and package provenance.</p></div><a className="text-link" href="https://github.com/FireStarsSoft/Bored-Manager/releases" target="_blank" rel="noreferrer">GitHub releases <ExternalLink size={14} /></a></div>{resource.loading ? <LoadingPanel label="Loading releases" /> : resource.error ? <ErrorPanel message={resource.error} retry={resource.reload} /> : !resource.data?.length ? <EmptyState title="No releases available">Release discovery is not enabled in this pre-alpha manager.</EmptyState> : <div className="release-list">{resource.data.map((release) => <article key={release.version} className={release.current ? "current" : ""}><div className="release-timeline"><i /><span /></div><div><header><h3>{release.version}</h3>{release.current && <Badge tone="success">Installed</Badge>}<Badge tone={release.channel === "stable" ? "success" : release.channel === "beta" ? "info" : "warning"}>{release.channel}</Badge>{release.signed && <Badge><ShieldCheck size={12} /> signed</Badge>}</header><p>{release.notes}</p><small>Published {dateTime(release.publishedAt)} / Agent {release.compatibleAgent}</small></div><Button variant="ghost" disabled={release.current}><Download size={15} /> {release.current ? "Current" : "View package"}</Button></article>)}</div>}</Panel>
  </div>;
}
